package microservices.priceCalculation;

import microservices.priceCalculation.CTypePriceCalculation.event.BTypeCalculatedEvent;

rule "over 89 free delivery"

    no-loop true

when

    $fact:BTypeCalculatedEvent(total < 89 , shopId == -1)

then

    $fact.setTotal($fact.getTotal() + 10);
    System.out.println( "<<!  order total less than 89,10 more for delivery: " + $fact.getUserId() + "  !>>");

end
